vim.o.shiftwidth = 4
vim.o.tabstop = 4
vim.o.signcolumn = 'yes:2'
vim.o.relativenumber = true
vim.o.termguicolors = true
vim.o.title = true
vim.o.ignorecase = true
vim.o.smartcase = true
vim.o.number = true
vim.o.splitright = true
vim.o.clipboard = 'unnamedplus'
vim.o.breakindent = true
vim.o.linebreak = true
vim.o.list = true
vim.o.listchars = 'tab:> ,lead:·,trail:·'
vim.o.scrolloff = 8
vim.o.sidescrolloff = 8
vim.o.updatetime = 250 -- Reduce time for highlighting other references
vim.o.redrawtime = 10000 -- Allow more time for loading syntax on large files
vim.o.showmode = false
